version: '3'

services:
  redis:
    build: .
    image: myredis
    privileged: true
    command: sh -c "./init.sh"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 26379:26379
